# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e81822e58851d43e92c5350e4afbabf62f42e1da20b865b8228087c9015b4195cc999f95bc8e04fb7778bb81c1efe314a5c17a6791bb80b1ff3547869f047f72

test:
  secret_key_base: 770ac5c15c38d2c75c6fe41feeb849cd1a17cc94fce4f8fbb91c25c69b1c7fceb22ba1ad8dc90a934016a4ef48cb3055980f9b8a08c2ec9d0295d0cae7969d56

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
